services:
  backend:
    container_name: modulebank_back
    build:
      context: .
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8001:8000"


  db:
    container_name: 'modulebank_bd'
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - my_network


volumes:
  db-data:

networks:
  my_network:
    external: true
